trigger:
- main  # Automatically trigger the pipeline on changes to the main branch

pool:
  name: VM  # Use your self-hosted agent pool
  demands:
    - agent.name -equals kingsrock  # Corrected format to match the self-hosted agent by name

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'  # Specify the required Python version
    addToPath: true

- script: |
    echo "Installing dependencies..."
    python -m pip install --upgrade pip
    pip install -r requirements.txt  # Install dependencies from the requirements.txt file
  displayName: 'Install Python dependencies'

- script: |
    echo "Running Streamlit app for testing..."
    streamlit run app.py --server.headless true  # Run the Streamlit app in headless mode
  displayName: 'Run Streamlit App (Headless)'

- script: |
    echo "Pipeline execution completed successfully!"  # Final message
  displayName: 'Finish Pipeline'
